# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/posthello-code/pre-commit-prettier
    rev: "3333cb1d1b3a4ab1cb3008c6eff40c5193fd761d" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
